apiVersion: v1
kind: Service
metadata:
  name: {{ include "aasoka-erp-chart.fullname" . }}
  namespace: production
  labels:
    {{- include "aasoka-erp-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "aasoka-erp-chart.selectorLabels" . | nindent 4 }}
